#我的一个配置的示例
#_config.yml

# Stalux 主题用户配置文件
# 这个文件优先级高于 _stalux.yml 默认配置
# 你只需要在这里配置想要修改的选项，其他选项会使用默认值

# 基础站点信息
title: "三清的博客"
titleDefault: "三清的博客"
siteName: "三清的博客"
author: "一气化三清"
enableViewTransitions: false  ## 是否启用视图转换效果，默认为 false

# 站点资源配置
favicon: "/stalux.ico"
avatarPath: "/images/pikaq2.jpg"

# SEO 核心配置，用于让搜索引擎（如百度、Google）更容易抓取、理解、收录你的博客内容，最终提升博客在搜索结果中的排名，获取更多免费的自然流量。
description: "探索、学习、进步、创造无限可能！"
short_description: "联系方式：w3120614845@outlook.com"
url: "https://sq422/sq422.github.io"
lang: "zh-CN"
locale: "zh_CN"
keywords: "Stalux, 博客主题, 内容创作, Astro主题, 静态网站生成器, SEO优化, 自定义博客, 响应式设计, 评论系统, 前端开发, Astro,ts,js"
canonical: "https://sq422/sq422.github.io"

# <head>元素硬嵌入
head:

# 站点导航配置 图标来自于https://feathericons.com/
nav:
  - title: "首页"
    path: "/"
    icon: "home"
  - title: "归档"
    path: "/archives/"
    icon: "archive"
  - title: "分类"
    path: "/categories/"
    icon: "folder"
  - title: "标签"
    path: "/tags/"
    icon: "tag"
  # - title: "友链"
  #   path: "/links/"
  #   icon: "link"
  # - title: "关于"
  #   path: "/about/"
  #   icon: "user"
  # - title: "开往"
  #   path: "https://www.travellings.cn/go.html"
  #   icon: "airplay"

# 站点特效配置
textyping:
  - "Free as in Freedom"
  - "Hello World!"
  - "弃我去者，昨日之日不可留"

# 社交媒体链接配置 ,图标来自于https://simpleicons.org/
medialinks:
  - title: "Github"
    url: "https://github.com/sq422"
    icon: "github"
  - title: "Bilibili"
    url: "https://space.bilibili.com/74192901"
    icon: "bilibili"
  # - title: "QQ"
  #   url: "https://qm.qq.com/q/64L8hnwQ2k"
  #   icon: "qq"
  - title: "eMail"
    url: "mailto:w3120614845@outlook.com"
    icon: "maildotru"
  # - title: "稀土掘金"
  #   url: "https://juejin.cn/user/1795939693507712"
  #   icon: "juejin"

# 评论系统配置 具体看WALINE src/layouts/BlogPost.astro 已屏蔽
# comment:
#   enabled: false # 是否启用评论系统，设置为false可关闭
#   waline:
#     serverURL: "xxx"
#     lang: "zh-CN"
#     reaction: false
#     meta:
#       - "nick"
#       - "mail"
#       - "link"
#     wordLimit: 200
#     pageSize: 10

# 友情链接配置
# friendlinks_title: "友情链接"
# friendlinks_description: "优质技术博客交换友情链接，互惠共赢提升网站流量和用户体验。期待与同领域高质量内容创作者建立长期合作关系。"
# friendlinks:
#   - title: "姓王者的博客"
#     url: "https://github.com/sq422/sq422.github.io"
#     avatar: "https://xingwangzhe.fun/avatar.webp"
#     description: "探索、学习、进步、创造无限可能！"

# 页脚配置
footer:
  buildtime: "2025-12-15T00:00:00"

  # 版权信息
  copyright:
    enabled: true
    startYear: 2024
    customText: ""

  # 主题信息
  theme:
    showPoweredBy: true
    showThemeInfo: true

  # 备案信息
  # beian:
  #   # ICP备案
  #   icp:
  #     enabled: true
  #     number: " 辽ICP备2024xxxxxx号-1"
  #   # 公安备案
  #   security:
  #     enabled: false
  #     text: "辽公网安备 XXXXXXXXXXXX号"
  #     number: "XXXXXXXXXXXX"

  # 徽章配置
  badges:
    - label: "Built with"
      message: "❤"
      color: "red"
      style: "for-the-badge"
      alt: "Built with Love"
      href: "https://github.com/sq422"
    - label: "Powered by"
      message: "Astro"
      color: "orange"
      style: "flat-square"
      alt: "Powered by Astro"
      href: "https://astro.build/"
    - label: "Theme"
      message: "Stalux"
      color: "blueviolet"
      alt: "Theme: Stalux"
      href: "https://stalux.needhelp.icu/"
    # - label: "license"
    #   message: "MIT"
    #   color: "blue"
    #   alt: "License: MIT"
    #   href: "https://github.com/xingwangzhe/stalux"
    # - label: "阿里云"
    #   message: "服务器"
    #   alt: "阿里云支持"
    #   href: "https://www.aliyun.com/minisite/goods?userCode=lmvvqvl9"
    - label: "Sitemap"
      message: "XML"
      color: "orange"
      alt: "Sitemap XML"
      href: "/sitemap-index.xml"
    - label: "RSS"
      message: "Feed"
      color: "orange"
      alt: "RSS Feed"
      href: "/rss.xml"
    - label: "Atom"
      message: "Feed"
      color: "orange"
      alt: "Atom Feed"
      href: "/atom.xml"
    # - label: "LLMs"
    #   message: "Dataset"
    #   color: "blue"
    #   alt: "LLM Dataset"
    #   href: "/llms.txt"


